server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-steep-field-a1cmfxpi-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_Bc2XQTbkUID4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # use 'validate' or Flyway for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  
